### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by lsteiner9** [tunefull/tunefull-service#2]
**Rubric:** https://ddc-java-11.github.io/2020/11/09/capstone-milestone-2-rubric/
- [x] Website organization/linking information/classes
- [x] Team roster (3 pts)
- [x] Project description (5 pts)
- [x] Intended users/user stories (5pts)
- [x] Wireframe (10 pts)
- [x] ERD (7 pts)
- [x] Entity classes (10 pts)
- [x] DDL (10 pts)
- [x] Repository interfaces (10 pts)
- [x] OAuth 2.0 resource server (15 pts)
- [x] REST controllers and application logic services (20 pts)
- [x] Javadoc documentation (15 pts)
- [x] Double-check everything!
